### ISSUE TITLE
Accessibiity problems and HTML Validation

### ISSUE THREAD

**Issue by guisantosfr** [guisantosfr/Clipboard-Landing-Page#1]
Accessibiity problems found:
1. Document should have one main landmark. **Context**: `<html lang="en">`
2. All page content should be contained by landmarks. **Contexts**: all sections

HTML Validation problem found:
1. Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections. Context: `<section class="sponsors">`

Any changes to the html document (classnames, for example) should also be changed in scss, preferably without layout changes.

**Comment by rajmunkhan** [comment]
@guisantosfr I would like to work on this, please assign it to me

**Comment by guisantosfr** [comment]
Thanks! It worked :)
